server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
#keycloak:
#  server:
#    contextPath: /auth
#    adminUser:
#      username: bael-admin
#      password: pass
#    realmImportFile: baeldung-realm.json

spring:
  #  security:
  #    oauth2:
  #      resource-server:
  #        jwt:
  #          issuer-uri: http://localhost:8083/auth/realms/baeldung
  #          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  datasource:
    password: pas
    url: jdbc:h2:mem:newsler
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000