server:
#  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver

#  mail:
#    host: localhost
#    port: 1025
#    username: admin
#    password: admin
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

logging:
  pattern:
    dateformat: "dd/MM/yyyy HH:mm:ss"