server:
  port: 8443
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  tomcat:
    accesslog:
      enabled: true

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password: pass
    url: jdbc:h2:mem:newsler
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  pattern:
    dateformat: "dd/MM/yyyy HH:mm:ss"