newsler:
  service:
    schema: http
    port: 8080
    domain-name: localhost
  designer:
    schema: http
    port: 4200
    domain-name: localhost

server:
  error:
    include-binding-errors: always
    include-stacktrace: always
    include-message: always
    include-exception: true
    whitelabel:
      enabled: true

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password: pass
    url: jdbc:h2:mem:newsler
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    throw-exception-if-no-handler-found: true
    problemdetails:
      enabled: true
  thymeleaf:
    check-template-location: false

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    test-connection: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        http: trace
  pattern:
    dateformat: "dd/MM/yyyy HH:mm:ss"