# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by separate terms of service, privacy policy, and support documentation.
#
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#
# For java see: https://github.com/actions/setup-java

name: Newsler CI with Gradle on Windows

on:
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 12 * * 5' # Runs at 12:00 UTC on Fri.

permissions:
  contents: read

jobs:
  MailDev-Start:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - name: Run maildev container
        run: ./gradlew runMailDevContainer

  Gradle-Build-Ubuntu:
    timeout-minutes: 30
    strategy:
      matrix:
        node: [16, 18]
    runs-on: windows-latest
    needs: [MailDev-Start]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'gradle'

      - name: Install Node modules
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Stop and delete maildev container
        run: ./gradlew deleteMailDevContainer

  MailDev-Stop:
    timeout-minutes: 30
    needs: [MailDev-Start]
    steps:
      - name: Run maildev container
        run: ./gradlew runMailDevContainer